<?php
$title = 'Kết quả tìm kiếm cho "' . $searchtxt . '"';
$this->headTitle($title);
?>

<div class="container">
    <h3><?php echo $title; ?></h3>
</div>
<div class="container">
    <div class="destinations">
        <div class="destination-places">
            <div class="wrap">
                <div class="destination-places-grids">
                    <div id="list-recommend">
                        <?php
                        foreach ($searchvalue as $placeSearch):
                            ?>
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 destination-places-grids" >
                                <div class="dest-place-pic main_box user_style4" data-hipop="two-horizontal">
                                    <a href="/place/detail?placeId=<?php echo $placeSearch->placeId; ?>"><img id="img-recommend" src="../images/<?php echo $placeSearch->imgUrl; ?>"/></a>
                                </div>
                                <div class="dest-place-opt">
                                    <ul class="dest-place-opt-cast">
                                        <li><a id="placeName" class="d-place" href="#"><?php echo $placeSearch->placeName; ?></a></li>
                                        <li><a id="placeAddress" class="d-price" href="#"><?php echo $placeSearch->address; ?></a></li>
                                        <div class="clear"> </div>
                                    </ul>
                                </div>
                            </div>
                            <?php
                        endforeach;
                        ?>
                    </div>
                </div>

            </div>
        </div>	
    </div>
</div>