<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('../css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/jquery.bxslider.js'))
                ->prependFile($this->basePath('js/flexy-menu.js'))
                ->prependFile($this->basePath('js/jquery-ui.min.js'))
                ->prependFile($this->basePath('js/css3-mediaqueries.js'))
                ->prependFile($this->basePath('js/fwslider.js'))
        ?>
        <script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    </script>
    <script src="../js/jquery.min.js"></script>
    <!---script---->
    <link rel="stylesheet" href="../css/zalki_hover_img.css" type="text/css" />
    <link rel="stylesheet" href="../css/jquery.bxslider.css" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <script src="../js/jquery.bxslider.js"></script>
    <script src="../js/jquery.flexisel.js"></script>
    <script src="../js/jquery.flexslider.js"></script>
    <script src="../js/jquery.zalki_hover_img.min-0.2.js"></script>
<!--    <script type="text/javascript">
        $(document).ready(function () {
            $('.bxslider').bxSlider({
                auto: true,
                autoControls: true,
                minSlides: 4,
                maxSlides: 4,
                slideWidth: 450,
                slideMargin: 10
            });
        });
    </script>-->
    <!---//script---->
    <!---smoth-scrlling---->
    <script type="text/javascript">
        $(document).ready(function () {
            $('a[href^="#"]').on('click', function (e) {
                e.preventDefault();
                var target = this.hash,
                        $target = $(target);
                $('html, body').stop().animate({
                    'scrollTop': $target.offset().top
                }, 1000, 'swing', function () {
                    window.location.hash = target;
                });
            });
        });
    </script>
    <!---//smoth-scrlling---->
    <!----start-top-nav-script---->
    <script type="text/javascript" src="../js/flexy-menu.js"></script>
    <script type="text/javascript">$(document).ready(function () {
            $(".flexy-menu").flexymenu({speed: 400, type: "horizontal", align: "left"});
        });</script>
    <!----//End-top-nav-script---->
    <!---webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!---webfonts---->
    <!--start slider -->
    <link rel="stylesheet" href="../css/fwslider.css" media="all">
    <script src="../js/jquery-ui.min.js"></script>
    <script src="../js/css3-mediaqueries.js"></script>
    <script src="../js/fwslider.js"></script>
    <!--end slider -->
    <!---calender-style---->
    <link rel="stylesheet" href="../css/jquery-ui.css" />
    <!---//calender-style---->
</head>
<body>
    <div class="header">
        <!----start-wrap---->
        <!----start-top-header----->
        <div class="top-header" id="header">
            <div class="wrap">
                <div class="top-header-left">

                    <div id="regbar">
                        <div id="navthing">
                            <ul>
                                <?php
                                $user_session = new Zend\Session\Container('user');
                                $username = $user_session->acc;
                                $user = $user_session->user;
                                if (!$user) {
                                    ?>
                                    <li><a href="#" class="loginform" id="loginform"><span> </span> Đăng nhập</a></li>
                                    <li><a href="../customer/register" class="loginform"><span> </span> Đăng kí</a></li>
                                    <?php
                                } else {
                                    $user_session = new Zend\Session\Container('user');
                                    ?>
                                    <li>
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" type="button" data-toggle="dropdown"><a style="cursor: pointer"><span> </span>Xin chào! <?php echo $user->name; ?></a>
                                                <p class="caret"></p></div>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" href="../customer/edit?userId=<?php echo $user->userId; ?>">Sửa thông tin</a></li>
                                                <li><a class="dropdown-item" href="../booktour/history">Lịch sử đặt tour</a></li>
                                            </ul>
                                        </div>
                                    </li>
                                  
                                    <li><a class="loginform" href="../logout"><span> </span> Đăng xuất</a></li>
                                <?php } ?>
                                <li><p class="contact-info">Liên hệ tổng đài : 01646161571</p></li>
                                <div class="clear"> </div>
                            </ul>
                            <div class="login">
                                <div class="arrow-up"></div>
                                <div class="formholder">
                                    <div class="randompad">
                                        <fieldset>
                                            <form action="..\login" method="GET">
                                                <input type="text" class="form-control" placeholder="Email" id="query" name="acc">
                                                <br>
                                                <input type="password" class="form-control" placeholder="Mật khẩu" id="query" name="pass">
                                                <br>
                                                <input class="btn" type="submit" value="Đăng nhập" />
                                            </form>
                                        </fieldset>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="top-header-right">
                    <ul>
                        <li><a class="face" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                        <li><a class="twit" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                        <li><a class="thum" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                        <li><a class="pin" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                        <div class="clear"> </div>
                    </ul>
                </div>
                <div class="clear"> </div>
            </div>
        </div>

        <!----//End-top-header----->
        <!---start-header---->

        <div class="wrap">
            <!--            - start-logo--
            <div class="logo">
                <a href="/application"><img src="../images/logo.png" title="voyage" /></a>
            </div>
            - //End-logo--
            - start-top-nav--
            <div class="top-nav">
                <ul class="flexy-menu thick orange">
                    <li class="showhide right" style="display: none;">
                        <span class="title">MENU</span>
                        <span class="icon">
                            <em style="background: red;"></em><em style="background: red;"></em><em style="background: red;"></em><em></em>
                        </span>
                    </li>
                    <li class="right" style=""><a href="/blog">Cẩm nang du lịch</a></li>
                    <li class="right" style=""><a href="/place">Địa điểm du lịch</a></li>
                    <li class="right" style=""><a href="/tour">Tour</a></li>
                    <li class="right" style=""><a href="/application">Trang chủ</a></li>
                </ul>
                <div class="search-box">
                    <div id="sb-search" class="sb-search">
                        <form>
                            <input class="sb-search-input" placeholder="Nhập nội dung tìm kiếm..." type="search" name="search" id="search">
                            <input class="sb-search-submit" type="submit" value="">
                            <span class="sb-icon-search"> </span>
                        </form>
                    </div>
                </div>

                
            </div>
            - //End-top-nav--

            <div class="clear"> </div>-->

            <nav class="navbar ">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span> 
                        </button>
                        <div class="logo" href="#"><a href="/application"><img src="../images/logo.png" title="voyage" /></a></div>
                    </div>
                    <div class="collapse navbar-collapse thick orange " id="myNavbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="showhide right" style="display: none;">
                                <span class="title">TÙY CHỌN</span>
                                <span class="icon">
                                    <em style="background: red;"></em><em style="background: red;"></em><em style="background: red;"></em><em></em>
                                </span>
                            </li>
                            <li class="right" style=""><a href="/application">Trang chủ</a></li>
                            <li class="right" style=""><a href="/tour">Tour</a></li>
                            <li class="right" style=""><a href="/place">Địa điểm du lịch</a></li>
                            <li class="right" style=""><a href="/recommendation">Đề xuất cho bạn</a></li>
                            <li class="right" style=""><a href="/blog">Cẩm nang du lịch</a></li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <div class="search-box">
                                <div id="sb-search" class="sb-search">
                                    <form method="GET" action="/place/search">
                                        <input class="sb-search-input" placeholder="Nhập nội dung tìm kiếm..." type="search" name="search" id="search">
                                        <input class="sb-search-submit" type="submit" value="">
                                        <span class="sb-icon-search"> </span>
                                    </form>
                                </div>
                            </div>
                            <!----search-scripts---->
                            <script src="../js/modernizr.custom.js"></script>
                            <script src="../js/classie.js"></script>
                            <script src="../js/uisearch.js"></script>
                            <script  src="../js/index.js"></script>
                            <script>
        new UISearch(document.getElementById('sb-search'));
                            </script>
                            <!----//search-scripts---->
                        </ul>
                    </div>

                </div>


        </div>
    </div>

</nav>

<!---//End-header---->

<div class="main-contain">
    <div class="container">
        <?php
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_ERROR, array('alert', 'alert-danger'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_INFO, array('alert', 'alert-info'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_WARNING, array('alert', 'alert-warning'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_DEFAULT, array('alert', 'alert-info'));
        ?>
    </div> 
    <?= $this->content ?>
</div>
<div class="clear"></div>
<!----start-footer---->
<div class="footer">
    <div class="wrap">
        <div class="footer-grids" style="width: 100%; text-align: center;">
            <div class="" style="text-align: center">
                <div class="address-info">
                    <span><i>VOYAGE</i> </span>
                    <br>
                    <span>Tầng 1, 70-72 Bà Triệu, Quận Hoàn Kiếm, Hà Nội</span>
                    <br>
                    <span>E-mail:<a href="mailto:voyage@gmail.com"> voyage@gmail.com</a></span>
                </div>
                <!--                <div class="footer-social-icons">
                                    <ul>
                                        <li><a class="face1 simptip-position-bottom simptip-movable" data-tooltip="facebook" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                                        <li><a class="twit1 simptip-position-bottom simptip-movable" data-tooltip="twitter" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                                        <li><a class="tub1 simptip-position-bottom simptip-movable" data-tooltip="tumblr" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                                        <li><a class="pin1 simptip-position-bottom simptip-movable" data-tooltip="pinterest" href="https://www.facebook.com/HuyenChep.PT"><span> </span></a></li>
                                        <div class="clear"> </div>
                                    </ul>
                                </div>-->
            </div>

        </div>
        <div class="clear"> </div>
    </div>
</div>
<!----//End-footer---->
<!---start-subfooter---->
<div class="subfooter">
    <div class="wrap">
        <ul>
            <li><a href="/application">Trang chủ</a><span>::</span></li>
            <li><a href="/tour">Tour</a><span>::</span></li>
            <li><a href="/place">Địa điểm du lịch</a><span>::</span></li>
            <li><a href="/recommendation">Đề xuất cho bạn</a><span>::</span></li>
            <li><a href="/blog">Cẩm nang du lịch</a></li>
            <div class="clear"> </div>
        </ul>
        <a class="to-top" href="#header"><span> </span> </a>
    </div>
</div>
<!---//End-subfooter---->
<!----//End-wrap---->
<?= $this->inlineScript() ?>
</body>
</html>
