<?php
$title = 'Thông tin chi tiết đặt tour ' . $tour->tourName;
$this->headTitle($title);
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<div class="container">
    <h3><?php echo $title; ?></h3>
</div>
<!---strat-date-piker---->

<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>
<!---/End-date-piker---->
<div class="row">
    <div class="container" >
        <div class="wrap" style="display: flex">
            <div class="left container-form" > 
                <?php
//                $form->setAttribute('action', $this->url('recommendation', ['action' => 'index']));
//                $form->setAttribute('method', 'post');
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class="contact-form">
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('tourId')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('userId')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('bookDate')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('seatNumber')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('price')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('unit')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('paid')); ?>
                    </div>
                    <div class="contact-to row">
                        <?php echo $this->formRow($form->get('status')); ?>
                    </div>

                    <div class="contact-to row">
                        <span> <?php echo $this->formRow($form->get('submit')); ?> </span>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                    <div class="clear"></div>
                </div>

            </div>
            <div class="right">
                <div class="contact-to row">
                    <table class="table">
                        <thead>
                        <th colspan="2">
                            <label>Thông tin chi tiết của tour</label>
                        </th>
                        </thead>
                        <tr>
                            <td>
                                <label>Tên tour</label>
                            </td>
                            <td>
                                <span><?php echo $tour->tourName; ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Đơn giá</label>
                            </td>
                            <td>
                                <span><?php echo $tour->price.' '.$tour->unit; ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Thời gian</label>
                            </td>
                            <td>
                                <span><?php echo $tour->dateStart.' đến '.$tour->dateEnd; ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Tổng số chỗ</label>
                            </td>
                            <td>
                                <span><?php echo $tour->seatNumber; ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label>Phương tiện</label>
                            </td>
                            <td>
                                <span><?php echo $tour->transport; ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <img src="../images/<?php echo $tour->image; ?>"/>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />
<!-- FlexSlider -->
<script defer src="js/jquery.flexslider.js"></script>